package com.telewave.battlecommand.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.telewave.battlecommand.db.NaviMsg;

import com.telewave.battlecommand.db.NaviMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig naviMsgDaoConfig;

    private final NaviMsgDao naviMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        naviMsgDaoConfig = daoConfigMap.get(NaviMsgDao.class).clone();
        naviMsgDaoConfig.initIdentityScope(type);

        naviMsgDao = new NaviMsgDao(naviMsgDaoConfig, this);

        registerDao(NaviMsg.class, naviMsgDao);
    }
    
    public void clear() {
        naviMsgDaoConfig.clearIdentityScope();
    }

    public NaviMsgDao getNaviMsgDao() {
        return naviMsgDao;
    }

}
